@startuml Diagrama
title Diagrama Prontuario Hospitalar 


class CID{
    - cid: String  
    + construtor //

}
class Paciente{
    - nome: String 
    - endereco: String 
    - documento: Int
    - nascimento: Date 
    - telefone: String 
    - telefone_emer: String
    - prontuario: Prontuario 
    + construtor (nome, endereco, documento, nascimento, telefone, telefone_emer)
    + alteracao 1 //
}

class Profissional{ 
    - nome: String
    - tipo_conselho: String

    //fazer construtor 
}

class Servico{
    - codigo_serv: int
    + construtor //
}

class Leito{
    - un_internacao: String
    - tipo_leito: String
    + construtor //
}
class Prescricao{
    - item: String
    - profissional: Profissional
}

class Prontuario{ 
    //recebe todo mundo
    - paciente: Paciente
    - cid: CID 
    - prescricao: Prescricao
    - id_prontuario: Int

    - medico: Medico //expandir profissionais

}    

